### ISSUE TITLE
do we need to add a back button?

### ISSUE THREAD

**Issue by harrietmilner** [thompsonbrandpartners/nexusinfographic#1]
I feel like we need a back button on each section. once you go past the first stage the only back you can go back is once you've selected your sector and specialism, but if you make a mistake there is no way to go back. can this be added on all screens?

**Comment by chriskemm** [comment]
Can we update the browser history, so you can navigate with native browsers buttons?

This would be a good tech fix.

Then a back arrow/button would be great, need input from a designer here. @chrisskelton

**Comment by thatswellwizard** [comment]
There is already a back to start link in use. To go back by a panel would be slightly more time consuming to do as it would need to to make sure it removes different data depending which panel you're on. Totally do-able though.

I don't feel like the browser button is the way to go as this tool is inside a website and the browser back button should probably move around the site instead

**Comment by harrietmilner** [comment]
Hey @thatswellwizard - @chriskemm is going to chat about this with you this afternoon when you have a catch up. 

Cheers,

**Comment by chriskemm** [comment]
See #7 

I do think we need to stop the browser back button existing the page though. It should at least restart the infographic.
