### ISSUE TITLE
Text hard to read.

### ISSUE THREAD

**Issue by chriskemm** [thompsonbrandpartners/nexusinfographic#11]
It's really hard to read the text in caps, I guess this is a brand thing. 

I'm guessing everyone is happy with the design?

<img width="1549" alt="Screenshot 2019-03-25 at 20 26 38" src="https://user-images.githubusercontent.com/984617/54952055-fcd59a80-4f3c-11e9-950d-7999d78be1b4.png">

**Comment by chrisskelton** [comment]
This is more text than I ever saw in the design, and I agree... but it is also a 'branding thing'. I'd probably recommend spacing the lines out a bit more which should help a bit.

**Comment by chriskemm** [comment]
@thatswellwizard can we try some alternative backgrounds on each item, so it's a bit easier to scan over items?

**Comment by thatswellwizard** [comment]
@chriskemm Sorry, I missed your comment on this one. What do you want to try out?

**Comment by chriskemm** [comment]
These items are blurring into one, Chris S suggested adding an alternative background. 

But let's leave this for now.
