### ISSUE TITLE
Scrolling issue on mobile

### ISSUE THREAD

**Issue by chriskemm** [thompsonbrandpartners/nexusinfographic#15]
As your viewing the infographic within a scrollable div/window. When you scroll to the bottom of a list the whole page scrolls down and you come out of the window which is confusing.

I wonder if full screening the infographic we'll resolve this issue?

**Comment by thatswellwizard** [comment]
The only way to to stop that would be to not set the height. Meaning the height of the infographic would change depending how much content is on each screen. so the height would jump up & down. We could set it to full screen, but on smaller screens you'd still get the scroll
