### ISSUE TITLE
Second button on the progress bar shows up as blank on click - should this automatically show the second screen as no action has been taken yet?

### ISSUE THREAD

**Issue by harrietmilner** [thompsonbrandpartners/nexusinfographic#18]
![Screenshot 2019-03-29 at 11 15 25](https://user-images.githubusercontent.com/47242880/55229136-09474500-5214-11e9-842c-88a5f2a05dcf.png)

**Comment by thatswellwizard** [comment]
I think you just need to clearly your cache. I've tested this quite a few times and it's working for me

**Comment by chriskemm** [comment]
Cleared my cache in an incognito window, still doing it for me.

**Comment by chriskemm** [comment]
You can skip ahead basically and pages are blank. We just need to display the progress bar for navigating forward.
