### ISSUE TITLE
Copy to be amended on final screens across all

### ISSUE THREAD

**Issue by harrietmilner** [thompsonbrandpartners/nexusinfographic#2]
Copy to be amended, should read: 

To find out more about a potential research collaboration with us, get in touch with our team.

**Comment by harrietmilner** [comment]
![Screenshot 2019-03-22 at 19 23 08](https://user-images.githubusercontent.com/47242880/54848141-61dc8680-4cd8-11e9-900d-18042dba4b2d.png)

**Comment by thatswellwizard** [comment]
Is this right @harrietmilner ?
On that PDF you sent me with the clients notes on, there was a note on this sentence that suggested the text should be changed to just 'Find out more'. Can you confirm it wants changing please.

**Comment by harrietmilner** [comment]
Hey @thatswellwizard - yes this is correct. sorry for any confusion, it was only supposed to be the first few words that were amended as there was a .... after it. So please amend to the above. 

Thanks,
