### ISSUE TITLE
Infographic - Navigation

### ISSUE THREAD

**Issue by chriskemm** [thompsonbrandpartners/nexusinfographic#7]
On the note of a back button. Can the bottom navigation be clickable so you can get back?

Maybe an arrow and back text on a larger screen. 

<img width="765" alt="Screenshot 2019-03-25 at 19 51 33" src="https://user-images.githubusercontent.com/984617/54950235-bf6f0e00-4f38-11e9-956f-cf62579f83c8.png">

**Comment by chriskemm** [comment]
As per above, I suggest we have a back on one side and forward (if that would work)?

Drop down to just arrows on mobile?

![Screenshot 2019-03-28 at 13 56 42](https://user-images.githubusercontent.com/984617/55163396-9f6e6300-5161-11e9-90f3-9657eee9e093.png)

**Comment by chriskemm** [comment]
@jamiem89 could you input on the back button we happy? Not 100% sure it works.

**Comment by jamiem89** [comment]
I propose that we remove the back button from the selection screens, and replace with a cross icon in the top right. Then after we've selected a sector, that 'back to start' link could be replaced with 'back to sector select'...

So it would look like this: 
![Screenshot 2019-04-12 at 08 56 26](https://user-images.githubusercontent.com/5813643/56021260-e1baa700-5d00-11e9-84e4-6f3c062aea7a.png)

We might need a little back arrow as part of that link too :+1:

**Comment by chriskemm** [comment]
Sounds good thanks!
